[project]
name = "music-bot"
version = "1.2.5"
description = "Telegram Music Bot with full playback support using PyTdBot and PyTgCalls"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Ashok Shau", email = "ashokshau@t.me" },
]
keywords = [
    "telegram",
    "music",
    "bot",
    "async",
    "tdlib",
    "pytgcalls",
    "voicechat",
    "spotify",
    "ytmusic",
    "opensource",
    "pytdbot",
    "py-tgcalls",
    "yt-dlp",
]
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
    "Topic :: Communications :: Chat :: Telegram",
    "Topic :: Multimedia :: Sound/Audio :: Players",
    "Environment :: Console",
    "Framework :: AsyncIO",
]
dependencies = [
    "aiofiles>=25.1.0",
    "aiohttp>=3.13.5",
    "cachetools>=7.0.6",
    "kurigram>=2.2.22",
    "ntgcalls==2.2.1b3",
    "pillow>=12.2.0",
    "psutil>=7.2.2",
    "py-tgcalls>=2.2.12",
    "py-yt-search==0.7.0b2",
    "pycryptodome>=3.23.0",
    "pydantic>=2.13.3",
    "pymongo>=4.17.0",
    "pytdbot>=0.9.10",
    "pytgcrypto>=1.2.12",
    "python-dotenv>=1.2.2",
    "tdjson==1.8.63",
    "ujson>=5.12.0",
    "yt-dlp>=2026.4.10.235301.dev0",
]

[project.license]
file = "LICENSE"

[project.optional-dependencies]
dev = [
    "black",
    "ruff"
]

[project.scripts]
start = "src.__main__:main"

[project.urls]
Homepage = "https://github.com/FallenProjects/music-bot"
Source = "https://github.com/FallenProjects/music-bot"
"Issue Tracker" = "https://github.com/FallenProjects/music-bot/issues"

[tool.uv]
package = true

[tool.uv.sources]
pytdbot = { git = "https://github.com/pytdbot/client", rev = "main" }

[tool.setuptools]
packages = [
    "src",
]
